from app import db

class Element(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    atomic_number = db.Column(db.Integer, index=True, unique=True, nullable=False)
    symbol = db.Column(db.String(10), index=True, unique=True, nullable=False)
    name = db.Column(db.String(50), index=True, unique=True, nullable=False)
    atomic_mass = db.Column(db.Float, nullable=False)
    group = db.Column(db.Integer)
    period = db.Column(db.Integer)
    element_type = db.Column(db.String(50))
    description = db.Column(db.Text)
    appearance = db.Column(db.String(255), nullable=True)
    boil = db.Column(db.Float, nullable=True)
    density = db.Column(db.Float, nullable=True)
    discovered_by = db.Column(db.String(255), nullable=True)
    melt = db.Column(db.Float, nullable=True)
    molar_heat = db.Column(db.Float, nullable=True)
    named_by = db.Column(db.String(255), nullable=True)
    phase = db.Column(db.String(50), nullable=True)
    source = db.Column(db.String(255), nullable=True)
    bohr_model_image = db.Column(db.String(255), nullable=True)
    bohr_model_3d = db.Column(db.String(255), nullable=True)
    spectral_img = db.Column(db.String(255), nullable=True)
    xpos = db.Column(db.Integer, nullable=True)
    ypos = db.Column(db.Integer, nullable=True)
    shells = db.Column(db.Text, nullable=True)
    electron_configuration = db.Column(db.String(255), nullable=True)
    electron_configuration_semantic = db.Column(db.String(255), nullable=True)
    electron_affinity = db.Column(db.Float, nullable=True)
    electronegativity_pauling = db.Column(db.Float, nullable=True)
    ionization_energies = db.Column(db.Text, nullable=True)
    cpk_hex = db.Column(db.String(10), nullable=True)
    image_title = db.Column(db.String(255), nullable=True)
    image_url = db.Column(db.String(255), nullable=True)
    image_attribution = db.Column(db.Text, nullable=True)
    block = db.Column(db.String(10), nullable=True)

    def __repr__(self):
        return f'<Element {self.name}>' 